### ISSUE TITLE
Нельзя получить больше 1000 записей

### ISSUE THREAD

**Issue by mad** [yandex-cloud/ydb-java-sdk#3]
Вне зависимости от заданного лимита возвращается только первая 1000 строчек, хотя в документации явно об этом не сказано, наоборот лимит не ограничен https://cloud.yandex.ru/docs/ydb/yql/reference/syntax/select#limit-offset

**Comment by oleshiy** [comment]
Большое спасибо за комментарий.
Мы детально опишем все ограничения YDB в документации.
Пока об этом написано только в FAQ https://cloud.yandex.ru/docs/ydb/faq#strings-limit
но мы постоянно работаем над улучшением документации

**Comment by mad** [comment]
Спасибо, понял
Это ограничение навсегда?

**Comment by mad** [comment]
Метод readTable принимает диапазон ключей

Таблица имеет вид:

`table (key string, column string, value string)` где key и column составной первичный ключ

Можно ли передавать диапазон из конкатенации key column?

**Comment by oleshiy** [comment]
> Спасибо, понял
> Это ограничение навсегда?

Думаю, что нет.
Мы активно работаем над расширением аналитических способностей YDB.

**Comment by oleshiy** [comment]
> Метод readTable принимает диапазон ключей
> Таблица имеет вид:
> `table (key string, column string, value string)` где key и column составной первичный ключ
> Можно ли передавать диапазон из конкатенации key column?

Можно передать Tuple из значений всех столбцов.

**Comment by mad** [comment]
Ок, спасибо
