### ISSUE TITLE
Пустая ошибка CLIENT_INTERNAL_ERROR на коммит

### ISSUE THREAD

**Issue by mad** [yandex-cloud/ydb-java-sdk#4]
Иногда на команду commit приходит ошибка  CLIENT_INTERNAL_ERROR, но в issues пустой массив

Идентификатор БД /ru-central1/b1g4ttmpjol8o9cnvlt3/etn00lmeuu8qek5om164 время ошибки 26.12 вечер

Возможно, в транзакции перемешано чтение и запись

**Comment by ZooKeeper** [comment]
Прошло очень много времени. Извини за долгий ответ.
Актуальна ли проблема?
